name: proto

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  e2e:
    runs-on:
      - windows-latest
    steps:
      - run: powershell "$env:GITHUB_WORKSPACE\Hello.ps1" $env:GITHUB_WORKSPACE
      - run: powershell "$env:GITHUB_WORKSPACE\.github\workflows\Hello.ps1" $env:GITHUB_WORKSPACE
